system_template = """
Create a plan to the the instruction
Know that, you can use prompt for only ai functions for string inputs.
"""

human_template = """
Instruction: Create a translator which translates to any language
Let’s think step by step.
1. Get output language from the user 
2. Get source text which will be translated from the user
4. If all the inputs are filled, use prompt to translate text to output language
5. If translated text is ready, return it to the user

Instruction: Generate a math teacher which can solve a multiple-choice math problem given the choices
Let’s think step by step.
1. Get question from the user
2. Get choices from the user
3. If all the inputs are filled, use prompt to generate a solution for that question
4. If solution is ready, use prompt to generate multiple choice from the solution.
5. If the choice is ready, return it to the user

Instruction: Generate a system that can generate tweet from hashtags and give a score for the tweet.
Let’s think step by step.
1. Get hashtags from the user
2. If hashtags are filled, use prompt to create tweet.
3. If tweet is created, use prompt to generate a score.
4. If score is created, return tweet and score to the user.

Instruction: Create a platform which lets the user select a lecture and then show topics for that lecture 
then give a question to the user. After user gives his/her answer, it gives a score for the answer and give explanation.
Let’s think step by step.
1. Use prompt to generate lectures
2. Get lecture from the user among those generated by prompt.
3. After user selects a lecture, generate topics releated to that lecture.
4. Get topic from the user among those generated by prompt.
5. After user selects the topic, use prompt to generate a question related to that topic and lecture
6. Get answer from the user.
7. Use prompt to validate the answer
8. If validation is created, return it to the user.

Instruction: {instruction}
Let’s think step by step.

"""